### ISSUE TITLE
DVDPLAYER.XLF file is missing

### ISSUE THREAD

**Issue by ab310714gz4700** [israpps/KELFBinder#10]
1st error:
Installation failed! (-201)
input KELF can't be opened

2nd error:
Installation failed! (-22)
KELF encryption Failed! - Possible 'MagicGate' error

Result:
DVD Player is not set up.

How to fix these errors?

**Comment by israpps** [comment]
> 1st error: Installation failed! (-201) input KELF can't be opened
> 
> 2nd error: Installation failed! (-22) KELF encryption Failed! - Possible 'MagicGate' error
> 
> Result: DVD Player is not set up.
> 
> How to fix these errors?

Due to copyright reasons, DVDPlayer software is not bundled with KELFBinder, user must provide the KELF.
