### ISSUE TITLE
Erro KELFBinder install

### ISSUE THREAD

**Issue by rona-lang** [israpps/KELFBinder#16]
I install kelfbind and when I start it gives an error in the configuration file and when I check with WLAUNCHELF the configuration file.INI is .INI.TXT I change it to .INI and it works on the next restart

**Comment by israpps** [comment]
?

**Comment by israpps** [comment]
no response or clarification of the exact issue in 2 weeks

**Comment by rona-lang** [comment]
I'm sorry but it's the config.ini.txt file when I install KELFBinder and it will give BOOT and it didn't recognize it so I renamed it to .uni and it worked
![17114833739485580403497136136056](https://github.com/israpps/KELFBinder/assets/151059034/d77667a3-7775-4786-9871-816b480f013b)

**Comment by israpps** [comment]
> I'm sorry but it's the config.ini.txt file when I install KELFBinder and it will give BOOT and it didn't recognize it so I renamed it to .uni and it worked ![17114833739485580403497136136056](https://private-user-images.githubusercontent.com/151059034/317021647-d77667a3-7775-4786-9871-816b480f013b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODUxODcsIm5iZiI6MTcxMTQ4NDg4NywicGF0aCI6Ii8xNTEwNTkwMzQvMzE3MDIxNjQ3LWQ3NzY2N2EzLTc3NzUtNDc4Ni05ODcxLTgxNmI0ODBmMDEzYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQyMDI4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmZmNTMzMzhhM2UwMzQ2MDY1ZjBjYWI1M2VlNDkyMmNmMWE5ZWYxYjE2MTM2Mzc0NzEzODg3YzZiNjBkZDkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rt4vJxMIym2bLApd5TD_meXK9fmqvNTsCvZJHhTBF4A)

1) this is not related to KELFBinder
2) this is not an issue because you renamed the file, CONFIG.INI is copied without renaming after install

**Comment by rona-lang** [comment]
![17114852604257553085649164179771](https://github.com/israpps/KELFBinder/assets/151059034/e4d8bb45-fbcf-4305-987c-31d2f0c092bf)

what I mean is that it is already included in the installation package

**Comment by rona-lang** [comment]
It already came like this in the kelfbinder package

**Comment by israpps** [comment]
> ![17114852604257553085649164179771](https://private-user-images.githubusercontent.com/151059034/317031631-e4d8bb45-fbcf-4305-987c-31d2f0c092bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODU4MDUsIm5iZiI6MTcxMTQ4NTUwNSwicGF0aCI6Ii8xNTEwNTkwMzQvMzE3MDMxNjMxLWU0ZDhiYjQ1LWZiY2YtNDMwNS05ODdjLTMxZDJmMGMwOTJiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQyMDM4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTE4ZDg4Yzk2YmVjMDE0YTc3ZGJjZWM0MmIwNjVjOTBjYzBiZGJlMmE4MTQyNzg3YTJmYmFlMTVkOWMyNDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SN8vumRyPkxEAId9LY4GenxKL9FLGkEsHkJjlOWrGkM)
> 
> what I mean is that it is already included in the installation package

yes, with the appropiate name. not with the `.txt` extra

**Comment by rona-lang** [comment]
Ok, thank you very much, your work is excellent, it saved my life because I no longer use a matrix chip, I am always following your projects, thanks.
