### ISSUE TITLE
access to boot rom broke due to SDK path normalization 

### ISSUE THREAD

**Issue by axmccx** [israpps/KELFBinder#19]
I copied the contents of [KELFBinder.7z](https://github.com/israpps/KELFBinder/releases/download/latest/KELFBinder.7z) to my USB drive. I started the KELFBinder.elf using FreeMcBoot and wLaunchELF, and I get this error: 
![IMG_5224](https://github.com/israpps/KELFBinder/assets/3931007/c878955c-9f44-4f0b-b517-bf170d900195)

**Comment by axmccx** [comment]
I just tried the [v1.1.1](https://github.com/israpps/KELFBinder/releases/tag/v1.1.1) build and it appears to be working fine.

**Comment by israpps** [comment]
Yes, it was an SDK update broke path normalization for rom0

Should be fixed in 5 mins

**Comment by axmccx** [comment]
That's for the quick fix! If I want to update from 1.1.1, should I rerun the installer, or could I get away with coping a few files to my memory card?

**Comment by axmccx** [comment]
I see the release was updated today, but I tried that version and getting the exact same error.

**Comment by israpps** [comment]
> I see the release was updated today, but I tried that version and getting the exact same error.

Are you sure??
Because the SDK update that caused this got reverted

**Comment by axmccx** [comment]
I'm certain, I just tried running `KELFBinder.elf` from [here](https://github.com/israpps/KELFBinder/releases/download/latest/KELFBinder.7z), and I get the same error.

**Comment by israpps** [comment]
Ok.

Please create a file in this path:

```
INSTALL/CORE/txtlog.opt
```

And run the program again, a text log file should be generated, paste it here pls

**Comment by axmccx** [comment]
I made the file at the directory you mentioned, it's on my USB drive at `E:\KELFBinder\INSTALL\CORE\txtlog.opt`. I then tried running the app (`E:\KELFBinder\KELFBinder.elf`) again to see the error screen, and the file is still empty.

![image](https://github.com/israpps/KELFBinder/assets/3931007/36137551-9b5c-465c-b819-50fe093a983e)

**Comment by israpps** [comment]
> I made the file at the directory you mentioned, it's on my USB drive at `E:\KELFBinder\INSTALL\CORE\txtlog.opt`. I then tried running the app (`E:\KELFBinder\KELFBinder.elf`) again to see the error screen, and the file is still empty.
> 
> ![image](https://private-user-images.githubusercontent.com/3931007/313441430-36137551-9b5c-465c-b819-50fe093a983e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NDM3MzAsIm5iZiI6MTcxMDY0MzQzMCwicGF0aCI6Ii8zOTMxMDA3LzMxMzQ0MTQzMC0zNjEzNzU1MS05YjVjLTQ2NWMtYjgxOS01MGZlMDkzYTk4M2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTdUMDI0MzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTEwZTE1OTg4YmYwMmM2NjllYzYzNjA5OGNhMTYyZjgxOWNhZjgxMTU5NmJlNmMzOGJhZGRhMDUyODI2YjdhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rsPMSgj7P_qw8I-K8GyunZ25puuMi_bkxJ9RRrD22QE)

Nono, the log will be written to a text file along the ELF.

Check again

**Comment by axmccx** [comment]
Ah my bad. It generated this `KELFBinder_log.txt` file, but it's empty
![image](https://github.com/israpps/KELFBinder/assets/3931007/c71e8a5e-2a11-4271-bf4d-6ea4e185b8d0)

**Comment by israpps** [comment]
> Ah my bad. It generated this `KELFBinder_log.txt` file, but it's empty ![image](https://private-user-images.githubusercontent.com/3931007/313441913-c71e8a5e-2a11-4271-bf4d-6ea4e185b8d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NDQ0MTksIm5iZiI6MTcxMDY0NDExOSwicGF0aCI6Ii8zOTMxMDA3LzMxMzQ0MTkxMy1jNzFlOGE1ZS0yYTExLTQyNzEtYmY0ZC02ZWE0ZTE4NWI4ZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTdUMDI1NTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODdlZjVhYzQyOTA3MGIyZjJlMDcxNDY1MDY2N2RmYmFlMWFlOWQyZWMzNmQzYjUzY2RiODBhNDcwNzVhYmZjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dMTswvoU8lbnf7QK654ucjUCohN7xtXo28rJHz7Uito)

Great, another thing the SDK broke!

**Comment by axmccx** [comment]
Thanks for having a look! I tried the [latest backup build](https://github.com/israpps/KELFBinder/releases/tag/latest-safe), and that works fine. It appears that also contains the latest version of PS2BBL, so should be good to use? 

I also noticed that compared to booting discs using the 1.1.1 release, the latest-safe fixes the game-id issue I was having when starting original PS2 discs. However I'm only able to start them with `$CDVD_NO_PS2LOGO` (holding Triangle). If I start a disc with `$CDVD`, (holding X), with the config.ini having `SKIP_PS2LOGO = 0`, I see the PS2 boot logo, but then it brings me to the Browser screen. If I try to start the game from there, it's just a black screen.

**Comment by israpps** [comment]
> also contains the latest version of PS2BBL

No, I forgot to encrypt the latest one IIRC. Anyways, it should be good to use still.

> I see the PS2 boot logo, but then it brings me to the Browser screen. If I try to start the game from there, it's just a black screen.

I can't do anything there, if logo shows up and the goes to browser then it's the PS2LOGO program that's rejecting the disc, not PS2BBL
