### ISSUE TITLE
White screen: Not able to find KELFBinder.lua on my USB drive

### ISSUE THREAD

**Issue by RoboMWM** [israpps/KELFBinder#28]
I've been trying to install ps2bbl so I can use an exFat USB with OPL. I have FreeMcBoot, and have been using the LaunchELF in that to start KELFBinder, following the system update method in https://www.youtube.com/watch?v=k1rYXCFaD9Q

Unfortunately, without fail, I hit the white screen with both the latest build (June 6, 2024, `47a71442ac614694a313156e0c90e7b321ace019`), the latest backup build, and v1.1.1 (though with v1.1.1 instead of white screen it explicitly says `CANNOT OPEN INSTALL/KELFBinder.lua: No such process`)

I've also tried using wLaunchELF_ISR (which I launch from FreeMcBoot's LaunchELF) (https://github.com/israpps/wLaunchELF_ISR/releases/tag/latest, `bc17c7dc8525530490fc1b96e8a552d9d584a57d`) (though I used the BOOT-EXFAT.elf - I see that I probably should've just got BOOT.elf, but I presume this shouldn't matter) with the exact same results.

I tried wLaunchELF (not ISR version), but it was unable to see my USB drive.

I'm always formatting the USB as FAT32 with each attempt.

I have been using my fat PS2:
- SCPH-30001
- Browser 1.20
- CD Player 1.20
- PlayStation Driver 1.10
- DVD Player 1.30U
No hard drive or expansion slot. I have not tried with a slim PS2.

I tried creating `INSTALL/CORE/txtlog.opt` but have not found any `KELFBinder_log.txt` file.

**Comment by israpps** [comment]
seems like u are using gpt format

**Comment by israpps** [comment]
> No - I ensured USB drive is using MBR, and I don't think Windows allows you to initialize as GPT for USB flash drives anyways (as far as I'm aware)
> 
> (My thinking is uLaunchELF also wouldn't be able to see the drive if it were GPT?)

most likely the usb drivers dont like your usb

**Comment by israpps** [comment]
Made a small USB test app

If you manage to setup a connection between PS2CLIENT on a PC and the PSW you can run the ELF that says UDPTTY on the filename and receive on your computer a full log of all the involved modules, either USB driver or FATFS manager

https://www.mediafire.com/folder/9xyzmsp0b2m30/USBTESTER

**Comment by RoboMWM** [comment]
https://github.com/ps2homebrew/Open-PS2-Loader/issues/1311#issuecomment-2327445583 seems to 'fix' my USB.

The original plan of me trying to use this to install ps2bbl was to get OPL working with exFAT, though I now see that's not needed as it uses its own drivers, plus with BDMAssault I can boot FreeMcBoot without crashing. I'm assuming I can have FreeMcBoot automatically boot into OPL via using its Configurator. If this is all I desire to do, is there any benefit in me trying to install and use ps2bbl anyway?
