### ISSUE TITLE
[ISSUE]: rom0 Access Denied

### ISSUE THREAD

**Issue by Gymyk** [israpps/KELFBinder#31]
### Checks

- [X] I have checked [__existing issues__](https://github.com/israpps/PlayStation2-Basic-BootLoader/issues) for duplicates and found none
- [X] I am using a build downloaded from [this repository](https://github.com/israpps/PlayStation2-Basic-BootLoader/releases)

### Describe the issue

Launching KELFBinder.elf from ulaunchelf with both FreeDVDBoot and FMCB and two separate drives created this error every time for me. I intended to install PS2BBL to a standard 8MB MagicGate memory card. 

One of the drives was a 1gb FAT usb drive, which I also tried FAT32 on, and the other was a 128gb FAT32 SD card. The only thing I did not try was putting the elf directly onto the FMCB memory card and adding it to the main menu.

The exact error message was something along the lines of 
Requested file could not be accessed
rom0:ROMVER

### Console model

SCPH-39001

### Program version (if possible, also provide hash)

v1.2.0

### What kind of boot method are you using to run the bootloader?

System Update

**Comment by Kupodad** [comment]
I'm sad to report that this new installer is no bueno. When launching it, it goes to a black screen and stays there. No info or error messages.

FAT PS2 30001. No mod chips. No hard drive. Just USB and a previous version of PS2BBL on a memory card. No reasons to believe there's anything wrong or unusual with this PS2.

**Comment by israpps** [comment]
More PS2SDK issues it seems...

Will debug it when I have some free time

**Comment by Lutrus-P** [comment]
> I'm sure this will be addressed in due time. I really wanted to run the greatest and latest (don't ask), so here's what I did:
> 
> 1. Download the November 2023 version. Extract to SD:\Frankenkelf
> 2. Download the latest version. Extract it to a temp folder.
> 3. Replace the following files/folder on your SD:\Frankenkelf from the latest version:
> 
> * The whole INSTALL\CORE folder
> * The whole INSTALL\KELF folder
> * The whole INSTALL\ASSETS\BOOT
> * The whole INSTALL\ASSETS\SYS-CONF  (new)
> 
> 4. Proceed with installation on your PS2
> 5. On your new PS2BBL memory card, make sure you have the SYS-CONF folder. If not, manually copy it over.
> 6. If everything went well, you shouldn't need the PS2BBL folder on your memory card (you can delete it).
> 
> This worked for me, and I'm confident-ish I'm now running the latest version. YMMV.

Unfortunately, this workaround doesn't work for me. It gets stuck at 0% during install. 😞

**Comment by Lutrus-P** [comment]
@Kupodad Are you sure you did exactly as you wrote? I followed the exact same steps but unfortunately it's not working. Perhaps you were using a different version from Nov 2023?

**Comment by israpps** [comment]
@fjtrujy @uyjulian seems like something is messed up on IOPRP Usage (libiopreboot)
```log
read/write allocate memory 4000
argv[0] = 'host:C:UsersUsuarioDesktopKELFBinderKELFBinder.elf'
KELFBINDER: Compiled on Dec  7 2024 18:48:53
Get Reboot Request From EE
PlayStation 2 ======== Soft reboot
IOP Realtime Kernel Ver.0.9.1
    Copyright 1999 (C) Sony Computer Entertainment Inc.
Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15)
iop heap service (99/11/03)
loadmodule: fname rom0:SYSCLIB args 0 arg
loadmodule: id 25, ret -2
loadmodule: fname rom0:UDNL args 11 arg img0:
file 'img0:' can't open
```

**Comment by Kupodad** [comment]
It now launches as expected :)

Thanks a lot!!

**Comment by israpps** [comment]
Very cool!

**Comment by Lutrus-P** [comment]
Yes, @israpps . Thank you so much, PS2BBL is awesome.
