### ISSUE TITLE
KELFBinder update not install

### ISSUE THREAD

**Issue by Helxgamer** [israpps/KELFBinder#7]
Hello dear developer how are you?

I came through this to report that the new version of KELFBinder is not installing on my console, it hangs on the loading screen with the white bar, since the version prior to PS2BBL with massX support is working normally.

hope this helps , I 'm excited to use the new version .

**Comment by israpps** [comment]
Please, create file called `txtlog.opt` inside `INSTALL/CORE/` folder

Run program again, then provide the log file generated by the program

**Comment by Helxgamer** [comment]
I did what you asked, but the log file was not being recorded, and the installer opened only once and caused the magic gate to fail, I redid it using another pendrive, the log was generated and I managed to install this time, I believe it is from my USB device, despite having managed to install more than once earlier today with the same pendrive but in the previous version, could it be drivers perhaps? finally follow the logs I got, thanks in advance

**Comment by Helxgamer** [comment]
> NEW LOG SESSION:
KELFBINDER: Compiled on Jul 20 2023 02:48:38

DEV9 device driver v1.0 - Copyright (c) 2003 Marcus R. Brown

dev9: CXD9611 detected.
dev9: SPEED chip '(unknown)', revision 13
dev9: CXD9611 (SSBUS Buffer) driver start.
[DEV9]: ret=0, ID=41
ATA device driver v1.2 - Copyright (c) 2003 Marcus R. Brown
atad: Driver loaded.
 [ATAD]: ret=0, ID=42
hdd: PS2 APA Driver v2.5 (c) 2003 Vector
hdd: max open = 4, 20 buffers
hdd: 05:06:07 03/04/2000
atad: Error: Unable to detect HDD 0.
hdd: Error: ata initialization failed.
 [PS2HDD]: ret=1, ID=43
CheckHDD: HDD status is -19
FINISHED LOADING IRX FILES
INITIALIZING POWEROFF
Hooking alternative poweroff
open name rom0:ROMVER flag 1 data 41378
open fd = 2

Graphics: created 640x448 video surface
initGraphics() Finished
PortMax: 2
SlotMax: 1
Please wait, pad(0,0) is in state EXECCMD
Pad OK!
The device has 2 modes
( 4 7 )It is currently using mode 15
Enabling dual shock functions
Please wait, pad(0,0) is in state EXECCMD
Pad OK!
infoPressMode: 1
enterPressMode: 1
Please wait, pad(0,0) is in state EXECCMD
Pad OK!
# of actuators: 2
padSetActAlign: 1
Please wait, pad(0,0) is in state EXECCMD
Pad OK!
pad_init() Finished
boot path : mass:KELFBinder/
running bootstring
Creating luaVM... 
Loading libs... luaGraphics_init done !
luaControls_init done !
luaScreen_init done !
luaTimer_init done !
luaSystem_init done !
luaRender_init done !
luaSecrMan_init done !
luaKELFBinder_init done !
luaHDD_init done !
done !
ROMVER	0220AC20050620
lua_KELFBinderInit: start
lua_getsystemregion: start

Graphics: created video surface of (704, 480)
KELFBinder.lua starts
lua_initsecrman: start
STARTING SECRMAN RPC BINDING
lua_getromversion: start
lua_initConsoleModel: starts
Embedd res: resource ID 5 requested!
luaP_loadHWCpng: Info: 0x31f590 421 5
Embedd res: resource ID 6 requested!
luaP_loadHWCpng: Info: 0x31f740 478 6
Embedd res: resource ID 15 requested!
luaP_loadHWCpng: Info: 0x32afe0 460 15
Embedd res: resource ID 13 requested!
luaP_loadHWCpng: Info: 0x32a0b0 3462 13
Embedd res: resource ID 12 requested!
luaP_loadHWCpng: Info: 0x3294d0 3030 12
Embedd res: resource ID 11 requested!
luaP_loadHWCpng: Info: 0x328f60 1383 11
Embedd res: resource ID 10 requested!
luaP_loadHWCpng: Info: 0x321720 30779 10
Embedd res: resource ID 0 requested!
luaP_loadHWCpng: Info: 0x31dde0 2219 0
Embedd res: resource ID 1 requested!
luaP_loadHWCpng: Info: 0x31e690 1826 1
Embedd res: resource ID 2 requested!
luaP_loadHWCpng: Info: 0x31edc0 1605 2
Embedd res: resource ID 7 requested!
luaP_loadHWCpng: Info: 0x31f920 2626 7
Embedd res: resource ID 8 requested!
luaP_loadHWCpng: Info: 0x320370 2129 8
Embedd res: resource ID 9 requested!
luaP_loadHWCpng: Info: 0x320bd0 2894 9
Embedd res: resource ID 3 requested!
luaP_loadHWCpng: Info: 0x31f410 167 3
Embedd res: resource ID 4 requested!
luaP_loadHWCpng: Info: 0x31f4c0 194 4
declaring installation tables for PS2BBL

checking path : mass:KELFBinder/INSTALL/ASSETS/PS2BBL
Installation table: 3 files listed to be moved from 'INSTALL/ASSETS/PS2BBL' to target:/PS2BBL'

checking path : mass:KELFBinder/INSTALL/ASSETS/APPS
Installation table: 3 files listed to be moved from 'INSTALL/ASSETS/APPS' to target:/APPS'

checking path : mass:KELFBinder/INSTALL/ASSETS/BOOT
Installation table: 3 files listed to be moved from 'INSTALL/ASSETS/BOOT' to target:/BOOT'

checking path : mass:KELFBinder/INSTALL/ASSETS/PS2BBL-HDD
Installation table: 1 files listed to be moved from 'INSTALL/ASSETS/PS2BBL-HDD' to target:/hdd0:__sysconf:pfs:/PS2BBL'

checking path : mass:KELFBinder/INSTALL/ASSETS/APPS-HDD
Installation table: 1 files listed to be moved from 'INSTALL/ASSETS/APPS-HDD' to target:/hdd0:__common:pfs:/APPS'

checking path : mass:KELFBinder/INSTALL/ASSETS/BOOT-HDD
Installation table: 1 files listed to be moved from 'INSTALL/ASSETS/BOOT-HDD' to target:/hdd0:__sysconf:pfs:/BOOT'

checking path : mass:KELFBinder/INSTALL/ASSETS/FSCK
Installation table: 16 files listed to be moved from 'INSTALL/ASSETS/FSCK' to target:/hdd0:__system:pfs:/fsck/lang'
MC installation table:
	[INSTALL/ASSETS/PS2BBL/CONFIG.INI] > [PS2BBL/CONFIG.INI]
	[INSTALL/ASSETS/PS2BBL/icon.sys] > [PS2BBL/icon.sys]
	[INSTALL/ASSETS/PS2BBL/PS2BBL.icn] > [PS2BBL/PS2BBL.icn]
	[INSTALL/ASSETS/APPS/APPS.icn] > [APPS/APPS.icn]
	[INSTALL/ASSETS/APPS/icon.sys] > [APPS/icon.sys]
	[INSTALL/ASSETS/APPS/OPNPS2LD.ELF] > [APPS/OPNPS2LD.ELF]
	[INSTALL/ASSETS/BOOT/BOOT.ELF] > [BOOT/BOOT.ELF]
	[INSTALL/ASSETS/BOOT/BOOT.icn] > [BOOT/BOOT.icn]
	[INSTALL/ASSETS/BOOT/icon.sys] > [BOOT/icon.sys]
HDD installation table:
	[INSTALL/KELF/HSYSTEM.XLF] > [hdd0:__system:pfs:/osd/osdmain.elf]
	[INSTALL/KELF/FSCK.XLF] > [hdd0:__system:pfs:/fsck/fsck.elf]
	[INSTALL/ASSETS/PS2BBL-HDD/CONFIG.INI] > [hdd0:__sysconf:pfs:/PS2BBL/CONFIG.INI]
	[INSTALL/ASSETS/APPS-HDD/OPNPS2LD.ELF] > [hdd0:__common:pfs:/APPS/OPNPS2LD.ELF]
	[INSTALL/ASSETS/BOOT-HDD/BOOT.ELF] > [hdd0:__sysconf:pfs:/BOOT/BOOT.ELF]
	[INSTALL/ASSETS/FSCK/fonts.txt] > [hdd0:__system:pfs:/fsck/lang/fonts.txt]
	[INSTALL/ASSETS/FSCK/labels_DU.txt] > [hdd0:__system:pfs:/fsck/lang/labels_DU.txt]
	[INSTALL/ASSETS/FSCK/labels_FR.txt] > [hdd0:__system:pfs:/fsck/lang/labels_FR.txt]
	[INSTALL/ASSETS/FSCK/labels_GE.txt] > [hdd0:__system:pfs:/fsck/lang/labels_GE.txt]
	[INSTALL/ASSETS/FSCK/labels_IT.txt] > [hdd0:__system:pfs:/fsck/lang/labels_IT.txt]
	[INSTALL/ASSETS/FSCK/labels_JA.txt] > [hdd0:__system:pfs:/fsck/lang/labels_JA.txt]
	[INSTALL/ASSETS/FSCK/labels_PO.txt] > [hdd0:__system:pfs:/fsck/lang/labels_PO.txt]
	[INSTALL/ASSETS/FSCK/labels_SP.txt] > [hdd0:__system:pfs:/fsck/lang/labels_SP.txt]
	[INSTALL/ASSETS/FSCK/NotoSans-Bold.ttf] > [hdd0:__system:pfs:/fsck/lang/NotoSans-Bold.ttf]
	[INSTALL/ASSETS/FSCK/strings_DU.txt] > [hdd0:__system:pfs:/fsck/lang/strings_DU.txt]
	[INSTALL/ASSETS/FSCK/strings_FR.txt] > [hdd0:__system:pfs:/fsck/lang/strings_FR.txt]
	[INSTALL/ASSETS/FSCK/strings_GE.txt] > [hdd0:__system:pfs:/fsck/lang/strings_GE.txt]
	[INSTALL/ASSETS/FSCK/strings_IT.txt] > [hdd0:__system:pfs:/fsck/lang/strings_IT.txt]
	[INSTALL/ASSETS/FSCK/strings_JA.txt] > [hdd0:__system:pfs:/fsck/lang/strings_JA.txt]
	[INSTALL/ASSETS/FSCK/strings_PO.txt] > [hdd0:__system:pfs:/fsck/lang/strings_PO.txt]
	[INSTALL/ASSETS/FSCK/strings_SP.txt] > [hdd0:__system:pfs:/fsck/lang/strings_SP.txt]
lua_getsystemregion: start
lua_getosdconfigLNG: start
FNTSYS Init
HDIOC_STATUS: -19

SLOT=0	type=2, freespace=4943, format=1, inforet=0
	mcSync.result=0 mcSync.syncret=1
SecrAuthCard start
card auth 0x60
mecha command:80 param: 08
mechacon auth 0x80
card auth key change
card auth 0x00
mecha command:81 param: 08
mechacon auth 0x81
card auth 0x01
card auth 0x02
mecha command:82 param: 01 11 a2 00 42 02 13 16 01 02 06 79 00 00 28 f1
mechacon auth 0x82
card auth 0x03
card auth 0x04
mecha command:83 param: 10 54 93 05 55 1c 81 7b
mechacon auth 0x83
card auth 0x05
mecha command:8f param:
mechacon auth 0x8f
mecha command:84 param:
mechacon auth 0x84
mecha command:85 param:
mechacon auth 0x85
card auth 0x06
card auth 0x07
card auth 0x08
card auth 0x09
card auth 0x0a
card auth 0x0b
card auth 0x0c
card auth 0x0d
card auth 0x0e
card auth 0x0f
card auth 0x10
card auth 0x11
mecha command:86 param: 07 b1 48 41 bd b5 7b a1 92 24 72 e4 8a 64 69 3c
mechacon auth 0x86
card auth 0x12
card auth 0x13
mecha command:87 param: f3 6e a0 b8 c5 6f 36 16
mechacon auth 0x87
mecha command:8f param:
mechacon auth 0x8f
card auth 0x14
mecha command:88 param:
mechacon auth 0x88

SLOT=1	type=2, freespace=7994, format=1, inforet=0
	mcSync.result=-1 mcSync.syncret=1

SLOT=0	type=2, freespace=4943, format=1, inforet=0
	mcSync.result=0 mcSync.syncret=1

SLOT=1	type=2, freespace=7994, format=1, inforet=0
	mcSync.result=0 mcSync.syncret=1
lua_getsystemregion: start
lua_getsystemupdatefolder: start

SLOT=1	type=2, freespace=7994, format=1, inforet=0
	mcSync.result=0 mcSync.syncret=1
lua_direxists: mc1:/BAEXEC-SYSTEM
	mc1:/BAEXEC-SYSTEM not found
lua_createDir: start
	mkdir: path 'mc1:/BAEXEC-SYSTEM'. result = 0
lua_calcsysupdatepath: start
lua_getsystemupdatefolder: start
adding copy protection to mc1:/BAEXEC-SYSTEM
	result was 0
--------------------
lua_secrdownloadfile: Starting with 4 argumments:
[Port]: 1
[Slot]: 0
[input KELF]: INSTALL/KELF/SYSTEM.XLF
[output KELF]: mc1:/BAEXEC-SYSTEM/osdmain.elf
[flags]: 0x0
lua_secrdownloadfile: input fd is 2
lua_secrdownloadfile: KELF size is 83604
SignKELF: start
	buffer_size=83604, port=1, slot=0
SecrDownloadFile: starts
SecrDownloadHeader: starts
header length 128
mecha command:90 param: 02 80 00 08 00
mecha command:8d param: 01 00 00 04 00 06 00 4a 00 0e 01 00 00 00 00 02
mecha command:8d param: 14 46 01 00 80 00 00 01 2c 02 00 00 ff 00 00 00
mecha command:8d param: a2 42 70 6c cb 23 33 98 29 80 d8 78 dc 68 ee f1
mecha command:8d param: 3b 0d 47 ff 20 2f 9f 54 3b 0d 47 ff 20 2f 9f 54
mecha command:8d param: 3b 0d 47 ff 20 2f 9f 54 7f 03 d2 a4 64 43 31 80
mecha command:8d param: 9e 05 0a 01 6d e2 d0 76 5b 89 bf b3 bf cd 01 fa
mecha command:8d param: 8b a7 0e 1e 0f c9 67 c5 75 22 24 ef de 97 b1 eb
mecha command:8d param: ac ae 9e d5 95 ca 9a f6 d3 3c 06 2c 20 43 f0 d4
mecha command:8f param:
mecha command:91 param:
mecha command:8e param:
mecha command:8e param:
mecha command:8e param:
SecrDownloadBlock: starts
mecha command:92 param: 10 00
mecha command:8d param: 2f 6a 99 53 03 6a 89 7d 68 84 63 c0 28 51 ad e1
mecha command:8f param:
SecrDownloadGetKbit: starts
mecha command:94 param:
mecha command:95 param:
card encrypt start
card encrypt 0x50
card encrypt 0x51
card encrypt 0x52
card encrypt 0x53
card encrypt start
card encrypt 0x50
card encrypt 0x51
card encrypt 0x52
card encrypt 0x53
kbit: { b3 33 26 de b2 ff 79 ef 8c a6 4d e9 c1 b1 23 a7  }
SecrDownloadGetKc: starts
mecha command:96 param:
mecha command:97 param:
card encrypt start
card encrypt 0x50
card encrypt 0x51
card encrypt 0x52
card encrypt 0x53
card encrypt start
card encrypt 0x50
card encrypt 0x51
card encrypt 0x52
card encrypt 0x53
kcontent: { 8c a6 4d e9 c1 b1 23 a7 8c a6 4d e9 c1 b1 23 a7  }
store_kbit: kbit_offset: 7070120
store_kc: kc_offset: 7070136
SecrDownloadFile complete
lua_secrdownloadfile: SignKELF returns 1
flags was empty, performing normal install!
lua_secrdownloadfile: [mc1:/BAEXEC-SYSTEM/osdmain.elf] fd is (2)
lua_secrdownloadfile: written 83604
lua_copyfile: Copying [INSTALL/ASSETS/USA.sys] to [mc1:/BAEXEC-SYSTEM/icon.sys]
lua_copyfile: Copying [INSTALL/ASSETS/PS2BBL.icn] to [mc1:/BAEXEC-SYSTEM/PS2BBL.icn]
lua_createDir: start
	mkdir: path 'mc1:/PS2BBL'. result = 0
lua_createDir: start
	mkdir: path 'mc1:/APPS'. result = 0
lua_createDir: start
	mkdir: path 'mc1:/BOOT'. result = 0
lua_copyfile: Copying [INSTALL/ASSETS/PS2BBL/CONFIG.INI] to [mc1:/PS2BBL/CONFIG.INI]
lua_copyfile: Copying [INSTALL/ASSETS/PS2BBL/icon.sys] to [mc1:/PS2BBL/icon.sys]
lua_copyfile: Copying [INSTALL/ASSETS/PS2BBL/PS2BBL.icn] to [mc1:/PS2BBL/PS2BBL.icn]
lua_copyfile: Copying [INSTALL/ASSETS/APPS/APPS.icn] to [mc1:/APPS/APPS.icn]
lua_copyfile: Copying [INSTALL/ASSETS/APPS/icon.sys] to [mc1:/APPS/icon.sys]
lua_copyfile: Copying [INSTALL/ASSETS/APPS/OPNPS2LD.ELF] to [mc1:/APPS/OPNPS2LD.ELF]
lua_copyfile: Copying [INSTALL/ASSETS/BOOT/BOOT.ELF] to [mc1:/BOOT/BOOT.ELF]
lua_copyfile: Copying [INSTALL/ASSETS/BOOT/BOOT.icn] to [mc1:/BOOT/BOOT.icn]
lua_copyfile: Copying [INSTALL/ASSETS/BOOT/icon.sys] to [mc1:/BOOT/icon.sys]
log file close requested
